eureka:
  client:
    register-with-eureka:
      value: true
    fetch-registry:
      value: true;
    service-url:
      defaultZone: http://eureka.herokuapp.com
    instance:
      hostname: localhost
