eureka:
  client:
    register-with-eureka:
      value: true
    fetch-registry:
      value: true;
    service-url:
      defaultZone: http://eureka.herokuapp.com
      non-secure-port: 80
      secure-port: 443
    instance:
      hostname: localhost
